# Generated by Django 4.2.16 on 2024-11-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
