# Generated by Django 4.2.16 on 2024-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_rename_body_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
